#define	DOWNLOAD_PROTO_HTTPS

#undef	SANBOOT_PROTO_ISCSI
#undef	SANBOOT_PROTO_AOE
#undef	SANBOOT_PROTO_IB_SRP
#undef	SANBOOT_PROTO_FCP

#undef	IMAGE_BZIMAGE

#define	VLAN_CMD
#define	PXE_CMD

#undef	BANNER_TIMEOUT
#define	BANNER_TIMEOUT	50
